/* eslint-disable typescript-eslint/ban-ts-comment, typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-examples.mts
// Do not edit this file directly.
import * as React from "react";

export const ExamplesIndex: Record<string, Record<string, any>> = {
  eve: {
    "openui-assistant": {
      component: React.lazy(async () => {
        const mod = await import("./eve/openui-assistant");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "openui-assistant";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/eve/openui-assistant.tsx",
      name: "openui-assistant",
    },
  },
  flue: {
    "openui-assistant": {
      component: React.lazy(async () => {
        const mod = await import("./flue/openui-assistant");
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || "openui-assistant";
        return { default: mod.default || mod[exportName] };
      }),
      filePath: "examples/flue/openui-assistant.tsx",
      name: "openui-assistant",
    },
  },
};
